### ISSUE TITLE
Cistern::Model#inspect raises TypeError when @identity is not defined

### ISSUE THREAD

**Issue by drbrain** [lanej/cistern#47]
The documentation says identity is ["not required"](https://github.com/lanej/cistern/blob/master/README.md#attributes) but if you don't have it defined as an attribute you can't inspect a `Model` instance:

```
$ ruby -rcistern -e 'class MyService < Cistern::Service; end; MyService::Model.new.inspect'
/…/gems/cistern-2.0.2/lib/cistern/attributes.rb:176:in `identity': nil is not a symbol nor a string (TypeError)
	from /…/gems/cistern-2.0.2/lib/cistern/model.rb:30:in `inspect'
	from -e:1:in `<main>'
```

**Comment by lanej** [comment]
@drbrain good catch. removed the identity requirement and refactored the formatters in https://github.com/lanej/cistern/commit/e04b8f32b5824ad23daae0379ce5949f5ee6a0e8.

Thanks for the report.

**Comment by lanej** [comment]
err, just kidding still doesn't work.

**Comment by lanej** [comment]
nvm, does actually work. Forgot to update my local gems

```
jlane@lanej p/cistern [master] » ruby -rcistern -e 'class MyService < Cistern::Service; end; MyService::Model.new.inspect'
/Users/jlane/.gem/ruby/2.2.2/gems/cistern-2.0.2/lib/cistern/attributes.rb:176:in `identity': nil is not a symbol nor a string (TypeError)
        from /Users/jlane/.gem/ruby/2.2.2/gems/cistern-2.0.2/lib/cistern/model.rb:30:in `inspect'
        from -e:1:in `<main>'
jlane@lanej p/cistern [master] » gem update cistern                                                     ‹2.2.2p95›[1]
Updating installed gems
Updating cistern
Fetching: cistern-2.0.3.gem (100%)
Successfully installed cistern-2.0.3
Gems updated: cistern
jlane@lanej p/cistern [master] » ruby -rcistern -e 'class MyService < Cistern::Service; end; MyService::Model.new.inspect'
```
